(defun xxx (a b) (+ a b))
(prin1 (xxx 3 4))
(defun x (x y) (+ x y))
(prin1 (x 10 20))
(defun x (x y) (- x y))
(prin1 (x 10 20))

(defun x nil)
(prin1 (x))

(defun x (x) (defun y (y) (prin1 (* x y))) (prin1 x) (y x))
(x 10)
(y 20)
(x 30)
(y 40)
