(prin1 (dotimes (i 3) (prin1 i)))
(prin1 (dotimes (i 3 i) (prin1 i)))
(prin1 (dotimes (i 3 i) (prin1 i) (prin1 (* i i))))
(prin1 (dotimes (i 0)))
(prin1 (dotimes (i 0 i)))
(dotimes (i (+ 2 3) (prin1 i)) (prin1 i))
(setq x nil)
(setq x (cons (dotimes (i 10 i) (setq x (cons i x))) x))
(prin1 x)
