(prin1 (type-of 1))
(prin1 (type-of 1.2))
(prin1 (type-of "fo"))
(prin1 (type-of t))
(prin1 (type-of nil))
(prin1 (type-of 'a))
(prin1 (type-of '1))
(prin1 (type-of '1.2))
(prin1 (type-of '"fo"))
(prin1 (type-of 't))
(prin1 (type-of 'nil))
(prin1 (type-of ''a))
(prin1 (type-of '(10 20)))
(prin1 (type-of (lambda (x) x)))
