(prin1 (cond))
(prin1 (cond (nil)))
(prin1 (cond (t)))
(prin1 (cond (t 10)))
(cond (t (prin1 1) (prin1 2)))
(defun x (x)
  (cond ((= x 1) (prin1 "one"))
        ((= x 2) (prin1 "two"))
        (t (prin1 "many"))))
(x 1)
(x 2)
(x 3)
