(dotimes (i 100)
  (let ((r (random 3)))
    (if (< r 0) (println "int out of range"))
    (if (> r 2) (println "int out of range"))))
(dotimes (i 100)
  (let ((r (random 2.5)))
    (if (< r 0.0) (println "float out of range"))
    (if (>= r 2.5) (println "float out of range"))))
(println "ok")
