(println (max 1 5 3))
(println (min 1 5 3))
(println (max 1.5 2))
(println (max 7))
(println (abs -3))
(println (abs 3))
(println (abs -3.5))
(println (expt 2 10))
(println (expt 2 0))
(println (expt 2 -1))
(println (expt 2.0 3))
(println (sqrt 4))
(println (sqrt 2))
