(println (string= "ab" "ab"))
(println (string= "ab" "ac"))
(println (string-upcase "aBc"))
(println (string-downcase "AbC"))
(println (subseq "hello" 1 3))
(println (subseq "hello" 2))
(println (subseq (list 1 2 3 4) 1 3))
(println (subseq (list 1 2 3) 1))
(println (subseq "abc" 0 0))
