(setq a 1)
(defun x () (setq a 2))
(x)
(print a)
(defun y ()
  (let ((a 3)) (print a))
  (print a)
)
(y)
(print a)
(let ((x 1)))
(let ((x 1) (y 2)) (print x) (print y))
(setq foo 1)
(let* ((foo 2) (bar foo))
  (print bar) (print foo))
(let ((foo 3) (bar foo))
  (print bar) (print foo))
