(println (eq 'a 'a))
(println (eq 'a 'b))
(println (eq 1 1))
(println (eql 1.0 1.0))
(println (eql 1 1.0))
(println (equal (list 1 2 (list 3)) (list 1 2 (list 3))))
(println (equal (list 1 2) (list 1 3)))
(println (equal "ab" "ab"))
(setq x (list 1 2))
(println (eq x x))
